### PR TITLE
Correct require statement to use correct file path

### PR DESCRIPTION
**Pull request by saishsali**

### CODE REVIEW

**Comment by saishsali** [comment]
@clue: Please review

**Comment by clue** [comment]
Thanks @saishsali!

I've just checked both examples, the paths appear to be correct as-is. Both examples have additional composer dependencies and hence their own `composer.json`, so they will need to install their dependencies to the local `vendor/` directory.

I understand that this could be confusing and at the very least could use some documentation. What are your thoughts on this?

**Comment by saishsali** [comment]
@clue: Both examples have their own compoer.json but third doesn't. Third one uses the root composer.json file. It might be confusing. We can use stick to one of the type to avoid confusion. Sorry for replying late.

**Comment by clue** [comment]
I'm undecided on this tbh, the good thing about 01-simple-periodic is that is does not require any additional dependencies and can be run as-is, while the others do require additional dependencies and require a dedicated installation step.

**Comment by saishsali** [comment]
@clue: The existing structure seems to be correct in that case. Closing this PR. Thanks :)

**Comment by clue** [comment]
For the reference: Structure of examples has just been simplified via #5 :+1:

**Pull request closed without merging**
