### PR TITLE
Update examples to newest ReactPHP HTTP-Server

### PR DESCRIPTION
**Pull request by legionth**
This PR will just update the current examples to use the current version of HTTP-Server.

It can maybe seen as part for #7.

### CODE REVIEW

**Comment by clue** [comment]
Nice! :tada: Really nice spot, didn't realize updating the HTTP component would be that easy :+1: 

Unfortunately, this currently causes an interesting issue: The `connect()` method will try to write all buffered data to the given stream instance. This will succeed, but simply discard all data, as the stream instance will only be passed to the response in the next step.

What do you think about this, do you see a simply fix for this or would this require a major refactoring?

**Comment by legionth** [comment]
Fair point. I will look into this.

**Comment by iNiSiRe** [comment]
Very sad that this PR is abandoned. I could help with the problem. Seems like there only one simple way to fix it without major refactoring:

Code with the issue:
```php
    $stream = new \React\Stream\ThroughStream();

    $stream->on('close', function () use ($stream, $channel) {
        echo 'disconnected' . PHP_EOL;
        $channel->disconnect($stream);
    });
    
    $channel->connect($stream, $id);

    return new \React\Http\Response(
        200, 
        array('Content-Type' => 'text/event-stream'), 
        $stream
    );
```

Resolved:
```php
    $stream = new \React\Stream\ThroughStream();

    $stream->on('close', function () use ($stream, $channel) {
        echo 'disconnected' . PHP_EOL;
        $channel->disconnect($stream);
    });

    $loop->nextTick(function () use ($channel, $stream, $id) {
        $channel->connect($stream, $id); 
    });

    return new \React\Http\Response(
        200,
        array('Content-Type' => 'text/event-stream'),
        $stream
    );
```

So after return the response the body will be piped to connection and in the next tick it's be able to send buffered messages. What do you think about this?

P.S.: Sorry for my English.

**Comment by legionth** [comment]
Hey @iNiSiRe ,

nice that you have still interest in this 👍 

Feel free to "hijack" this Pull Request, since I have currently no time to add new changes.
As far as I know @clue always appreciate PRs :)

**Comment by iNiSiRe** [comment]
@legionth, Hi.

Yes, SSE - is good alternative for WebSockets when needed communication only in one direction server -> client.

Thanks. Yes, I'll wait that @clue confirm this way is ok. (:

**Review by clue — COMMENTED** [review]
@iNiSiRe Thanks for looking into this, this does indeed seem to solve this problem :+1: Feel free to file a new PR with some additional tests and I'm happy to get this in! :shipit:

**Comment by clue** [comment]
@legionth Thanks for looking into this, I've just merged your changes with some additional updates in #11! :shipit:

**Pull request closed without merging**
